only_if: $CIRRUS_TAG == '' && ($CIRRUS_PR != '' || $CIRRUS_BRANCH == 'master')
auto_cancellation: $CIRRUS_BRANCH != 'master'
env:
  CARGO_INCREMENTAL: '0'
  CARGO_NET_GIT_FETCH_WITH_CLI: 'true'
  CARGO_NET_RETRY: '10'
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: '1'
  RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: '10'

freebsd_task:
  name: test ($TARGET)
  freebsd_instance:
    image_family: freebsd-12-4
  matrix:
    - env:
        TARGET: x86_64-unknown-freebsd
    - env:
        TARGET: i686-unknown-freebsd
  setup_script:
    - pkg install -y git
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable --target $TARGET
  test_script:
    # https://github.com/cirruslabs/cirrus-ci-docs/issues/483
    - sudo sysctl net.inet.tcp.blackhole=0
    - . $HOME/.cargo/env
    - cargo test --target $TARGET
    # Test async-io
    - git clone https://github.com/smol-rs/async-io.git
    - echo '[patch.crates-io]' >> async-io/Cargo.toml
    - echo 'polling = { path = ".." }' >> async-io/Cargo.toml
    - cargo test --target $TARGET --manifest-path=async-io/Cargo.toml
